### ISSUE TITLE
1.16.5 backport?

### ISSUE THREAD

**Issue by saltyseadoggo** [Lemonszz/rusty-iron#1]
Hello! I really love the concept of this mod, and especially the textures that you've made for it! What I don't love as much is that it can only be played on 1.17 snapshots, which not all Fabric mods currently support, and which, being snapshots, can have various stability issues, and can also receive sweeping changes to gameplay at unexpected times. As such, I would like to humbly ask if it would be possible for you to backport this mod to 1.16.5 in addition to its snapshot release, so that players stuck in this version because of other mods or who don't want to play on snapshots can play with it. If not, that is totally cool.~

Also, I apologise for opening an issue for a request; Discussions are not open on this repository.

**Comment by Lemonszz** [comment]
Yup, it's planned. No ETA.
