### ISSUE TITLE
Crash on Game Startup

### ISSUE THREAD

**Issue by 02mgmg** [Lemonszz/rusty-iron#4]
Upon startup of the game with the mod installed, the game crashes, giving this crash report:
[crash-2021-06-28_18.45.59-client.txt](https://github.com/Lemonszz/rusty-iron/files/6728224/crash-2021-06-28_18.45.59-client.txt)

P.S. sorry don't know how to label as a bug

**Comment by Khytwel** [comment]
I have the same crash on my side, Fabric 0.11.6.

**Comment by SquirrelCraft** [comment]
I can confirm crash. Using CureForge Launcher on MacOS using Fabric 11.6 and the only mod added was Rusted Iron(rusted_iron-21w01a-1.0.1.jar). I am doing some more testing to see if it is the Fabric version

**Comment by SquirrelCraft** [comment]
So after some testing, both rusted_iron-21w01a-1.0.1.jar and rusted_iron-21w01a-1.0.0.jar crash on CureForge Launcher on MacOS using Fabric 11.6, 11.5,11.3. My crash file looks the same as far what is throwing the error minus the system details. Also tried diff versions of the Fabric API. Do we know what version of the Fabric API is needed ?

**Comment by Lemonszz** [comment]
This isn't updated to 1.17. 
If you want to use it, you need to use 21w01a & whatever fabric api version was released for that version.
