### ISSUE TITLE
feature suggestion: make iron equipment rust based on durability

### ISSUE THREAD

**Issue by NixityNull** [Lemonszz/rusty-iron#7]
I think a cool addition would be if the texture of iron tools reflected their durability similar to the copper armor from https://www.curseforge.com/minecraft/mc-mods/copper-armor-tools-fabric, or alternatively took away durability slowly/became rusted variants over time when submerged in water

**Comment by Lemonszz** [comment]
We're not looking to add anything like that to the mod, sorry. 

I
