### ISSUE TITLE
Iron block slabs etc dont rust

### ISSUE THREAD

**Issue by ZEROX7** [Lemonszz/rusty-iron#8]
hey ther ei just installed your mod set random tick speed to 9999 and checkt if iron blocks slabs and stairs rust and they dont cut ones doo
![image](https://user-images.githubusercontent.com/12628051/171724160-ddc14f9e-48ef-447d-b6da-7875076780df.png)

**Comment by Lemonszz** [comment]
Seems to work on my end. 

Are you sure you didn't accidentally place down the waxed versions?

**Comment by ZEROX7** [comment]
yes
but i got immersive waethering installed could it be that it conflicts?
update after a long time the star rusted one stage

**Comment by Lemonszz** [comment]
Looks like there is actually an issues with slabs.

Unsure about the full blocks, but I'll look into it soon.

**Comment by ZEROX7** [comment]
note im running forge not fabric XD sry forgot that

**Comment by Lemonszz** [comment]
Fixed for 2.0.3
